import "./globals.css"
import { Inter } from "next/font/google"
import localFont from "next/font/local"
import base from "./base.scss"

const inter = Inter({ subsets: ["latin"] });
const Satoshi = localFont({
    src: [
        {
            path: './fonts/Satoshi-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
    ],
});

const ClashGrotesk = localFont({
    src: [
        {
            path: './fonts/ClashGrotesk-Regular.woff2',
            weight: '400',
            style: 'normal',
        }
    ]
})

export const metadata = {
    title: "Crealive",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={Satoshi.className}>{children}</body>
        </html>
    )
}

export function H1({title, className}) {
    return (
        <h1 className={ClashGrotesk.className + className}>{title}</h1>
    )
}

export function createTitle({ head }) {
    return head ? head : "no Data"
}

export function Header({ titleClass, heading, head }) {
    const list = ["Barış", "Claw", "Başka biri"]

    return (
        <div>
            <h1 className={titleClass ? titleClass : "bg-blue-300"}> {heading} {createTitle({ head })}</h1>
            <ul>
                {list.map((listItem) => (
                    <li key={listItem}>{listItem}</li>
                ))}
            </ul>
        </div>
    )
}
